### ISSUE TITLE
Bunkerweb 403 error

### ISSUE THREAD

**Issue by crabix** [notthebee/ansible-easy-vpn#52] opened 2022-08-13 13:55 UTC
i ran the plabook without trouble.

but entering wg.XXX.duckdns.org it show a "Forbidden 403" error.

The "docker log bunkerweb" show the following error message

2022/08/13 13:26:33 [error] 81#81: *18 directory index of "/opt/bunkerweb/www/" is forbidden, client: 12.34.567.899, server: [www.example.com](http://www.example.com/), request: "GET / HTTP/1.1", host: "wg.XXXXX.duckdns.org"

It might reference to the other issue.
https://github.com/notthebee/ansible-easy-vpn/issues/2

**Comment by notthebee** [comment] 2022-08-13 13:56
What about `docker logs authelia`

**Comment by crabix** [comment] 2022-08-13 14:00
only error messages are with the SMTP setup. seems like icloud has some issues.

**Comment by crabix** [comment] 2022-08-13 14:02
Ahhhh seeems that due to the SMTP error authelia does not start properly.

**Comment by crabix** [comment] 2022-08-13 15:54
I reinstalled everything this time without email configuration. authelia is error free

bunkerweb still shows

2022/08/13 15:45:50 [error] 82#82: *19 directory index of "/opt/bunkerweb/www/" is forbidden, client: 95.91.266.184, server: www.example.com, request: "GET / HTTP/1.1", host: "wg.XXXX.duckdns.org"
wg.crabix.duckdns.org 95.91.266.184 - - [13/Aug/2022:15:45:50 +0000] "GET / HTTP/1.1" 403 8488 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47"
2022/08/13 15:45:51 [notice] 82#82: *27 [BUNKERNET] Successfully reported IP 95.91.266.184 (reason : unknown), context: ngx.timer, client: 95.91.266.184, server: 0.0.0.0:8080

Any idea?

**Comment by notthebee** [comment] 2022-08-13 18:12
Is 95.91.266.184 your IP?

If yes, do `docker exec bunkerweb bwcli unban 95.91.266.184`

**Comment by crabix** [comment] 2022-08-13 18:20
unban worked:

docker exec bunkerweb bwcli unban 95.91.266.184
[2022-08-13 18:15:29] API - ℹ️ - Successfully sent API request to http://127.0.0.1:5000/unban


Unfortunately same error

2022/08/13 18:17:08 [error] 5871#5871: *1066 directory index of "/opt/bunkerweb/www/" is forbidden, client: 95.91.266.184, server: www.example.com, request: "GET / HTTP/1.1", host: "wg.xxx.duckdns.org"
wg.xxx.duckdns.org 95.91.266.184 - - [13/Aug/2022:18:17:08 +0000] "GET / HTTP/1.1" 403 8488 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.47"
2022/08/13 18:17:08 [notice] 5871#5871: *1067 [BUNKERNET] Successfully reported IP 95.91.266.184 (reason : unknown), context: ngx.timer, client: 95.91.266.184, server: 0.0.0.0:8080

**Comment by notthebee** [comment] 2022-08-13 18:24
You shouldn't have to unban it at all, and I'm not quite sure why it gets reported. Check if there are any prior log messages which state the reason why the IP was banned

**Comment by crabix** [comment] 2022-08-13 18:33
2022/08/13 16:42:45 [notice] 2896#2896: ModSecurity-nginx v1.0.2 (rules loaded inline/local/remote: 0/910/0)
2022/08/13 16:42:45 [notice] 2896#2896: signal process started
2022/08/13 16:42:46 [notice] 55#55: signal 1 (SIGHUP) received from 2896, reconfiguring
2022/08/13 16:42:46 [notice] 55#55: reconfiguring
[2022-08-13 16:42:46] SCHEDULER - ❌ - Error while reloading nginx

Thats repeated in the logs


2022/08/13 17:44:24 [error] 5871#5871: *827 [ACCESS] Error while calling access() on plugin blacklist : IP is not in list (error = error while trying to get reverse dns : name error), client: 111.7.100.20, server: www.example.com, request: "GET / HTTP/1.1", host: "xxx.duckdns.org"

and that occurs before the reporting messages once for every new IP address.

**Comment by notthebee** [comment] 2022-08-13 19:33
Could it be that you're accessing the server from a Chinese IP?
Chinese IPs are blocked by default in this configuration. 

If that's the case, remove the "BLACKLIST_COUNTRY" line from $HOME/ansible-easy-vpn/roles/bunkerweb/templates/env.j2 and re-run the playbook:
```
cd $HOME/ansible-easy-vpn
ansible-galaxy install -r requirements.yml
ansible-playbook run.yml
```

**Comment by crabix** [comment] 2022-08-13 19:58
Good old Germany behind Vodafone. So that can’t be it. Also the VPS is the same as yours from the YT video. Racknerd…

Any other idea?

**Comment by notthebee** [comment] 2022-08-13 20:05
Nope :( 

Just spun up the latest version of the repo on a fresh AWS instance and confirmed that everything works.
Let's keep the issue open for now, I'll take a look at the code and try to reproduce it

**Comment by notthebee** [comment] 2022-08-13 20:06
P.S. #2 shouldn't be relevant here anymore, because I've added additional checks to the `bootstrap.sh` script to make sure that both wg.domain.com and auth.domain.com resolve to the IP of the server

**Comment by crabix** [comment] 2022-08-13 20:08
I am sub for longer time and really appreciate your videos and dedication. Long story short…I would give you the VPs credentials if you want them :)

**Comment by crabix** [comment] 2022-08-13 20:18
of course via email or messenger and not here :)

**Comment by notthebee** [comment] 2022-08-14 12:19
Sorry, but I wouldn't feel safe doing that.

**Comment by crabix** [comment] 2022-08-14 14:39
The VPS is just my playground so no worries on that. Which Ubuntu did you use on racknerd? I am thinking of reinitalizing the VPS with Ubuntu 20.44 instead of 22.44. maybe that helps? 

I also remember that the URL did not show any SSL certificates so maybe some problem with let‘s encrypt…

**Comment by notthebee** [comment] 2022-08-14 14:47
I've tested it on both 20.04 and 22.04

Yes, you might want to try it with a different domain name, but I don't think that that's what's causing the 403 error

**Comment by notthebee** [comment] 2022-08-14 15:06
Feel free to shoot me the credentials: wolfgangschannel@mailbox.org

**Comment by crafttepid0n** [comment] 2022-08-14 23:17
I have installed it on multiple VPSs successfully. Today I did a fresh installation and am running into the same 403 bunkerweb error

**Comment by TheFirstMonster** [comment] 2022-08-14 23:43
> I have installed it on multiple VPSs successfully. Today I did a fresh installation and am running into the same 403 bunkerweb error

Same thing here, also had a successful instance running and now after a reinstall can't get it to work anymore.

**Comment by crafttepid0n** [comment] 2022-08-14 23:46
> > I have installed it on multiple VPSs successfully. Today I did a fresh installation and am running into the same 403 bunkerweb error
> 
> Same thing here, also had a successful instance running and now after a reinstall can't get it to work anymore.

Never touch a running system ... :)

**Comment by notthebee** [comment] 2022-08-15 07:03
@crabix If you're still interested in giving me your RackNerd credentials, I'd like to take a look at the issue. Send me an email

**Comment by crabix** [comment] 2022-08-15 08:07
sure! i just wanted to change the passwords before you get it but the rerun of the playbook after editing the secrets.yml does not have any effect. login via ssh still works only with old pw. i havent updated the vpn file with the public key but my understanding is that it should not be affected by the PW change.

**Comment by notthebee** [comment] 2022-08-15 08:18
Feel free to wipe the instance completely and regenerate the SSH password

**Comment by crabix** [comment] 2022-08-15 08:40
same thoughts. you just received everything via email :)

**Comment by TheFirstMonster** [comment] 2022-08-15 09:22
> > > I have installed it on multiple VPSs successfully. Today I did a fresh installation and am running into the same 403 bunkerweb error
> > 
> > 
> > Same thing here, also had a successful instance running and now after a reinstall can't get it to work anymore.
> 
> Never touch a running system ... :)

Well it was already more broken than running, so there's that...

**Comment by notthebee** [comment] 2022-08-15 09:29
> Well it was already more broken than running, so there's that...

Broken how?

**Comment by 3ighty2O** [comment] 2022-08-15 10:23
I have the same problem, can't find any solution for bunkerweb 403 so i went back to the video that people complaint and do it with ease. https://youtu.be/gxpX_mubz2A

**Comment by notthebee** [comment] 2022-08-15 10:26
Me and @crabix just went through the setup on his RackNerd VPS and I wasn't able to reproduce the issue – the script works and the Authelia WebUI is accessible after running the playbook.

It's possible that there was an outage on the side of Let's Encrypt during the weekend, but it still needs more investigation. @3ighty2O @TheFirstMonster try again when you have time, and see if the problem persists

**Comment by notthebee** [comment] 2022-08-15 10:39
P.S. DuckDNS seems to be down at the moment – my DuckDNS domain doesn't pass the Let's Encrypt challenge, wheras a Namecheap domain works.

**Comment by crabix** [comment] 2022-08-15 11:49
I guess it was in total a Lets Encrypt issue during the weekend. After reinitializing the server couple of times and notthebee helping with some sanity checking it all works now. So cool :)

**Comment by 3ighty2O** [comment] 2022-08-16 02:10
> P.S. DuckDNS seems to be down at the moment – my DuckDNS domain doesn't pass the Let's Encrypt challenge, wheras a Namecheap domain works.

Can I run both wireguard and openvpn on the same vps?

**Comment by notthebee** [comment] 2022-08-16 07:08
Yes, you can

**Comment by TheFirstMonster** [comment] 2022-08-16 09:25
> Me and @crabix just went through the setup on his RackNerd VPS and I wasn't able to reproduce the issue – the script works and the Authelia WebUI is accessible after running the playbook.
> 
> It's possible that there was an outage on the side of Let's Encrypt during the weekend, but it still needs more investigation. @3ighty2O @TheFirstMonster try again when you have time, and see if the problem persists

Just installed flawlessly

**Comment by notthebee** [comment] 2022-08-16 09:26
Good to hear. I will close the issue now :)

**Closed by notthebee** 2022-08-16 09:26 UTC
