### ISSUE TITLE
Playbook error - "Enable and start the iptables service" fails

### ISSUE THREAD

**Issue by dipamc** [notthebee/ansible-easy-vpn#221] opened 2023-08-17 18:31 UTC
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

The error seems to be same as Issue #212 , but their mentioned fix (reinstalling the OS) doesn't fix it for me. I've tried to check online how to start iptables and why it might be failing but so far I've been unsuccessful in fixing it.

**Logs** 
```
PLAY [Install and configure ansible-easy-vpn] ***********************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************
ok: [localhost]

TASK [Set the AWS and Letsencrypt staging facts] ********************************************************************************************************************
ok: [localhost]

TASK [system : Update the packages and configure auto-updates] ******************************************************************************************************
included: /root/ansible-easy-vpn/roles/system/tasks/setup.yml for localhost

TASK [system : Update and upgrade apt packages] *********************************************************************************************************************
ok: [localhost]

TASK [system : Install unattended upgrades package] *****************************************************************************************************************
ok: [localhost]

TASK [system : Copy unattended-upgrades configuration files in place] ***********************************************************************************************
changed: [localhost] => (item=10periodic)
changed: [localhost] => (item=50unattended-upgrades)

TASK [system : Configure the firewall] ******************************************************************************************************************************
included: /root/ansible-easy-vpn/roles/system/tasks/firewall.yml for localhost

TASK [system : Template the iptables rules] *************************************************************************************************************************
changed: [localhost]

TASK [system : Copy the iptables systemd service] *******************************************************************************************************************
changed: [localhost]
TASK [system : Enable and start the iptables service] ***************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg: |-
    Unable to start service iptables: Job for iptables.service failed because the control process exited with error code.
    See "systemctl status iptables.service" and "journalctl -xe" for details.

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=9    changed=3    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Environment:**
- Client OS: Mac OS 13
- VPS OS : Ubuntu 20.04
- VPS Provider: Racknerd
- System : 1.5 GB RAM 1 CPU

By the way, thanks a lot for putting together the tutorial on youtube and this easy to use playbook.

**Comment by bm-srdjanmarjanovic** [comment] 2023-08-30 07:28
+1 I have the same exact issue. Ubuntu 22.04 VM

**Comment by abdulazizalmass** [comment] 2023-09-02 05:47
so I have spent yesterday trying to fix the whole script and it worked. For this issue, the simple fix just restart your ubuntu and run an upgrade` do-release-upgrade`. This should take you to another release Ubuntu 20.04."something new here"

**Comment by opatotto** [comment] 2023-09-28 01:01
Same here even with the recommendation of  `do-release-upgrade` I still have the problem 

> so I have spent yesterday trying to fix the whole script and it worked. For this issue, the simple fix just restart your ubuntu and run an upgrade` do-release-upgrade`. This should take you to another release Ubuntu 20.04."something new here"

Same problem here, even with the recommendation of @abdulazizalmass I still have the problem. 

VPS Provider Racknerd
VPS OS : Ubuntu 20.04 and 20.04.3

**Comment by opatotto** [comment] 2023-09-28 02:30
I think I found the solution, you can try it to check if this works. The problem is the path of the iptables-restore is incorrect. This was my path: /usr/sbin/iptables-restore. You can see your path with 'which iptables-restore,' but the script was trying to execute on this path: /sbin/iptables-restore.

To solve this, you need to update the config file of iptables with `nano /etc/systemd/system/iptables.service` Ensure your path is correct on this line: `ExecStart=/usr/sbin/iptables-restore`. Save the file, and you will need to apply these commands: `systemctl daemon-reload`, then `sudo systemctl restart iptables`, and finally, check if the iptables are working with `sudo systemctl status iptables`

**Comment by DiMMMMM0N** [comment] 2023-09-28 03:12
> I think I found the solution, you can try it to check if this works. The problem is the path of the iptables-restore is incorrect. This was my path: /usr/sbin/iptables-restore. You can see your path with 'which iptables-restore,' but the script was trying to execute on this path: /sbin/iptables-restore.
> 
> To solve this, you need to update the config file of iptables with `nano /etc/systemd/system/iptables.service` Ensure your path is correct on this line: `ExecStart=/usr/sbin/iptables-restore`. Save the file, and you will need to apply these commands: `systemctl daemon-reload`, then `sudo systemctl restart iptables`, and finally, check if the iptables are working with `sudo systemctl status iptables`

iptables.service - Restore iptables firewall rules
     Loaded: loaded (/etc/systemd/system/iptables.service; enabled; vendor preset: enabl>
     Active: inactive (dead) since Thu 2023-09-28 03:10:28 UTC; 26s ago
   Main PID: 166351 (code=exited, status=0/SUCCESS)
        CPU: 4ms

**Comment by superconducter** [comment] 2023-10-03 20:14
for me the fix was to first install iptables and the update the path in the service file. 

steps to fix:
1. `sudo apt-get install iptables`
2. `nano /etc/systemd/system/iptables.service`  and add /usr/ to the path like so `ExecStart=/usr/sbin/iptables-restore`
3. `systemctl daemon-reload`

then run `systemctl restart iptables` to check if it works. if it does, rerun the script

**Comment by DiMMMMM0N** [comment] 2023-10-04 14:31
See ei tööta.

iptables.service - Restore iptables firewall rules
     Loaded: loaded (/etc/systemd/system/iptables.service; enabled; vendor preset: enabl>
     Active: inactive (dead) since Wed 2023-10-04 14:20:14 UTC; 6s ago
    Process: 1239960 ExecStart=/usr/sbin/iptables-restore -n /etc/iptables.conf (code=ex>
   Main PID: 1239960 (code=exited, status=0/SUCCESS)
        CPU: 5ms

**Comment by alisa4y** [comment] 2023-12-23 21:16
Hi 

For me the problem was it try to reading it from the /sbin path,

I fixed it with this:
`sudo ln -s /usr/sbin/iptables-restore /sbin/iptables-restore`

Make sure the iptables-restore path is right("/usr/sbin/iptables-restore"). you can find out with this command: 
`which iptables-restore`

If it was different replace the "/usr/sbin/iptables-restore" with it.

**Comment by notthebee** [comment] 2023-12-31 21:12
Fixed in https://github.com/notthebee/ansible-easy-vpn/commit/146c32c763e0ba5843908c2a4c68f45d167d61e4

**Closed by notthebee** 2023-12-31 21:12 UTC
