### ISSUE TITLE
not work correctly...

### ISSUE THREAD

**Issue by MajidValizadeh** [notthebee/ansible-easy-vpn#103] opened 2022-12-01 11:01 UTC
After typing the **domain name** & hitting enter nothing happened! 
[![Screenshot-2022-12-01-142556.png](https://i.postimg.cc/rFN0CxJv/Screenshot-2022-12-01-142556.png)](https://postimg.cc/ykW87J2P)

**Comment by notthebee** [comment] 2022-12-03 19:06
Duplicate of #90

**Closed by notthebee** 2022-12-03 19:06 UTC
