### ISSUE TITLE
nothing happend after i input domain name

### ISSUE THREAD

**Issue by Valdes11** [notthebee/ansible-easy-vpn#90] opened 2022-11-20 12:12 UTC
hello senpai's
after i input domain name nothing happend 
what should i do 
![Screenshot 2022-11-20 154152](https://user-images.githubusercontent.com/47695889/202901183-1d747e17-b555-4a74-9803-8045ceea4d8e.png)

**Comment by notthebee** [comment] 2022-11-20 13:19
It looks like you didn't press [Enter] after entering the domain name?

**Comment by Valdes11** [comment] 2022-11-20 13:30
hello there thank for the asnwer but for sure i did it!
 
would you like i give you my user pass you trying?

**Comment by Valdes11** [comment] 2022-11-20 13:33
and i have an ask if its possible for you pls make script for kerio i didnt find any usefull manual

**Comment by notthebee** [comment] 2022-11-20 13:54
Unfortunately, I can't provide individual support.

Are you sure that the host has internet access, working DNS, and that there isn't a firewall that would otherwise block outoging or incoming connections on 80/tcp or 443/tcp?

**Comment by Valdes11** [comment] 2022-11-20 14:15
i am sure that has internet access and ufw status 
![Screenshot 2022-11-20 174402](https://user-images.githubusercontent.com/47695889/202907112-25c03177-0936-4c62-b49e-4e2a86d63a1e.png)

**Comment by Valdes11** [comment] 2022-11-20 16:22
would you pls tell me how i can run manually this part of your precious project

**Comment by notthebee** [comment] 2022-11-20 16:23
I'm not sure what you mean. What part?

**Comment by Valdes11** [comment] 2022-11-20 16:23
after entering domain name sections

**Comment by Valdes11** [comment] 2022-11-20 16:25
sorry for man lang any way i am tottaly noob but i am from iran and we need vpns to keep our protesting indeed

**Comment by Valdes11** [comment] 2022-11-20 16:25
so thats why i am asking you too much :)

**Comment by notthebee** [comment] 2022-11-20 16:27
The domain name part has to succeed. It checks that your domain is accessible for Let's Encrypt, and that certbot can generate certificates for it. If it doesn't, there is something wrong with your network configuration.

Can you post the outputs of these commands here?
```
ping acme-staging-v02.api.letsencrypt.org
curl https://acme-staging-v02.api.letsencrypt.org
```

**Comment by Valdes11** [comment] 2022-11-20 16:31
yes i will 
root@Your-vps:~# ping acme-staging-v02.api.letsencrypt.org

PING acme-staging-v02.api.letsencrypt.org(2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026)) 56 data bytes
64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026): icmp_seq=1 ttl=57 time=2.63 ms
64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026): icmp_seq=2 ttl=57 time=2.70 ms
64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026): icmp_seq=3 ttl=57 time=2.71 ms
64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026): icmp_seq=4 ttl=57 time=2.78 ms
64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026): icmp_seq=5 ttl=57 time=2.61 ms
64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026): icmp_seq=6 ttl=57 time=2.71 ms
c64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026 (2606:4700:60:0:f41b:d4fe:4325:6026): icmp_seq=7 ttl=57 time=2.64 ms
^C64 bytes from 2606:4700:60:0:f41b:d4fe:4325:6026: icmp_seq=8 ttl=57 time=2.69 ms

--- acme-staging-v02.api.letsencrypt.org ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 35063ms
rtt min/avg/max/mdev = 2.606/2.681/2.777/0.051 ms
root@Your-vps:~#
curl https://acme-staging-v02.api.letsencrypt.org
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Boulder: The Let's Encrypt CA</title>

  <style type="text/css">
    header { display: flex; max-height: 30vh; flex-wrap: wrap; margin-bottom: 10vh; }
    header img { display: flex; max-height: 20vh; align-content: flex-end; margin-right: 20px; }
  </style>
</head>

<body>
  <header>
    <section>
      <img src="/static/images/LE-Logo-LockOnly.svg"/>
    </section>
    <section>
      <h1>Boulder<br>
      <small>The Let's Encrypt CA</small></h1>
    </section>
  </header>

  <section>
    <p>This is an <a href="https://tools.ietf.org/html/rfc8555">ACME</a> Certificate Authority running <a href="https://github.com/letsencrypt/boulder">Boulder</a>.</p>
    <p>This is a <em>programmatic</em> endpoint, an API for a computer to talk to. You should probably be using a specialized client to utilize the service, and not your web browser. See <a href="https://letsencrypt.org/docs"><tt>https://letsencrypt.org/docs</tt></a> for help.</p>
    <p>If you're trying to use this service, note that the starting point, <em>the directory</em>, is available at this URL: <a href="https://acme-staging-v02.api.letsencrypt.org/directory"><tt>https://acme-staging-v02.api.letsencrypt.org/directory</a></tt>.</p>
  </section>

  <footer>
      <p>
        <a href="https://letsencrypt.status.io" title="Status">Service Status (letsencrypt.status.io)</a> |
        <a href="https://twitter.com/letsencrypt" title="Twitter">Let's Encrypt Twitter</a>
      </p>
  </footer>

</body>
</html>
root@Your-vps:~#

**Comment by Valdes11** [comment] 2022-11-20 16:34
![Uploading Screenshot_2022-11-20-20-04-37-022_com.sonelli.juicessh.jpg…]()

**Comment by Valdes11** [comment] 2022-11-20 16:34
![Screenshot_2022-11-20-20-04-43-151_com sonelli juicessh](https://user-images.githubusercontent.com/47695889/202914007-a6dde01e-4122-4b72-bc8c-33b64c8a85e5.jpg)

**Comment by notthebee** [comment] 2022-11-20 16:36
Please refrain from posting screenshots and try to condense multiple replies into one message, it makes it easier to follow message threads.

Can you try re-running the playbook from scratch to make sure that it wasn't a temporary networking issue?
```
rm -rf $HOME/ansible-easy-vpn
wget https://notthebe.ee/vpn -O bootstrap.sh && bash bootstrap.sh
```

**Comment by Valdes11** [comment] 2022-11-20 16:43
oh sorry about that 
 but still nothing happend

**Comment by notthebee** [comment] 2022-11-23 08:36
I might have some time tonight to take a look at this more closely.
If you're willing to take the risk, email me the credentials at moe@notthebe.ee

**Comment by Valdes11** [comment] 2022-11-23 12:58
Hello again yea thank you very much if u looking at Address : 181.215.69.19/22User rootPass: Amir1369Os :ubuntu Any other information if u need tell I will send it to youThank you very much   Sent from Mail for Windows From: WolfgangSent: Wednesday, November 23, 2022 12:07To: notthebee/ansible-easy-vpnCc: Valdes11; AuthorSubject: Re: [notthebee/ansible-easy-vpn] nothing happend after i input domain name (Issue #90) I might have some time tonight to take a look at this more closely.If you're willing to take the risk, email me the credentials at ***@***.***—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Valdes11** [comment] 2022-11-23 13:00
And it would be my pleasure  Sent from Mail for Windows From: WolfgangSent: Wednesday, November 23, 2022 12:07To: notthebee/ansible-easy-vpnCc: Valdes11; AuthorSubject: Re: [notthebee/ansible-easy-vpn] nothing happend after i input domain name (Issue #90) I might have some time tonight to take a look at this more closely.If you're willing to take the risk, email me the credentials at ***@***.***—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by notthebee** [comment] 2022-11-23 13:02
Please don't post your password in clear text here. They're visible for everyone. Email me directly at the email above.

**Comment by Valdes11** [comment] 2022-11-23 13:37
ow sorry i just sent those information

**Comment by notthebee** [comment] 2022-12-03 19:08
Unfortunately I still didn't get the credentials from @Valdes11

The bug can't be reproduced on any of my systems, which makes it difficult to solve. It would be great someone else could like to help me diagnose it.

**Comment by MajidValizadeh** [comment] 2022-12-04 08:36
I have same problem here!(I opened a new issue section but closed it...) maybe I can help you out to figure it out with this issue! @notthebee

**Comment by notthebee** [comment] 2022-12-04 08:37
Yes, I closed your issue because it's a duplicate of this issue. Let's track it here

**Comment by MajidValizadeh** [comment] 2022-12-04 17:31
Thanks for your response! so what's next? what kind of info do you need to fix the issue? @notthebee

**Comment by notthebee** [comment] 2022-12-04 17:49
This thread suggests that IPv6 might be the issue: https://community.letsencrypt.org/t/letsencrypt-cli-hangs-on-certificate-request/27211/20

Try disabling IPv6 on your VPS and see if that helps

**Comment by MajidValizadeh** [comment] 2022-12-05 05:59
not working even after **disabling ipv6**!!!

**Comment by notthebee** [comment] 2022-12-05 07:22
What VPS provider are you on?

**Comment by MajidValizadeh** [comment] 2022-12-06 05:01
hostinger!

**Comment by notthebee** [comment] 2023-01-05 19:46
I haven't been able to reproduce this on any of my instances (Hetzner, Linode, RackNerd, AWS, AlexHost).

If someone would like to help, and let me borrow their Hostinger instance for 30 minutes, that would be amazing

**Closed** 2023-01-17 08:29 UTC
Labels: help wanted

**Comment by MajidValizadeh** [comment] 2023-01-19 16:46
This was a pretty weird issue for me! migrating my server to Hetzner shortly and checking that again... btw thanks!
